/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.nuevoPQRSMModelo;

/**
 *
 * @author Sala221
 */
public class FrmNuevoPQRSM extends javax.swing.JFrame {
        public String tipoqueja = "";
      public  String anexo1 = "";
       public String Recibo = ""; 
       
        nuevoPQRSMModelo modelo = new nuevoPQRSMModelo();
    /**
     * Creates new form NuevoPQRSM
     */
    public FrmNuevoPQRSM() {
        initComponents();
        
        asignarfecha();
    }
    
    public boolean isEmail(String correo){
            Pattern pat = null;
            Matcher mat =null;
            pat = Pattern.compile("^([0-9a-zA-Z]([_.W]*[0-9a-zA-Z])*@8[0-9a-zA-Z]"
                                  +"[-W]*[0-9a-Za-z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
            mat = pat.matcher(correo);
            if (mat.find()){
                return true;
            }
            else{
                return false;
            }
    }
    
    private void asignarfecha(){
    
        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            
            Date Fecha1 ;
            
            Fecha1 = formato.parse("01/01/1980 18:00:00");
            this.Fecha.setDate(Fecha1);
           Fecha.getDateEditor().setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(FrmNuevoPQRSM.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipouser = new javax.swing.ButtonGroup();
        Tipoqueja = new javax.swing.ButtonGroup();
        anexo = new javax.swing.ButtonGroup();
        recibo = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jtxtdocumento = new javax.swing.JTextField();
        Jtxtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtxtTel = new javax.swing.JTextField();
        JtxtDirecc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JtxtCel = new javax.swing.JTextField();
        JtxtMail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtxtdescrip = new javax.swing.JTextArea();
        JRBmanifes = new javax.swing.JRadioButton();
        JRBQueja = new javax.swing.JRadioButton();
        JRBReclamo = new javax.swing.JRadioButton();
        JRBsuge = new javax.swing.JRadioButton();
        JRBpeticion = new javax.swing.JRadioButton();
        JRBanexosi = new javax.swing.JRadioButton();
        JRBanexono = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtxtDescrip2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        Jtxtimagen = new javax.swing.JTextField();
        jBtnseleccionar = new javax.swing.JButton();
        JlblFoto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JRBreciformato = new javax.swing.JRadioButton();
        JRBrecimail = new javax.swing.JRadioButton();
        JRBrecitele = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        JCBCargo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        JCBfuncionario = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        JTxtApellido = new javax.swing.JTextField();
        JtxtTipousuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JtxtNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(759, 618));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("NUEVO PQRSM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Documento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombre:");

        Jtxtdocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtxtdocumentoFocusLost(evt);
            }
        });
        Jtxtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtdocumentoKeyTyped(evt);
            }
        });

        Jtxtnombre.setEnabled(false);
        Jtxtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtnombreKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Direccion:");

        JtxtTel.setEnabled(false);
        JtxtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtTelKeyTyped(evt);
            }
        });

        JtxtDirecc.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Celular:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("E-Mail:");

        JtxtCel.setEnabled(false);
        JtxtCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtCelKeyTyped(evt);
            }
        });

        JtxtMail.setEnabled(false);
        JtxtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtMailActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Descripcion");

        Jtxtdescrip.setColumns(20);
        Jtxtdescrip.setRows(5);
        jScrollPane1.setViewportView(Jtxtdescrip);

        Tipoqueja.add(JRBmanifes);
        JRBmanifes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        JRBmanifes.setText("MANIFESTACION DE SATISFACCION: Es la expresión de conformidad o reconocimiento por parte del usuario por un buen servicio recibido.");
        JRBmanifes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBmanifesActionPerformed(evt);
            }
        });

        Tipoqueja.add(JRBQueja);
        JRBQueja.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        JRBQueja.setText("QUEJA: Manifestación de insatisfacción expresada por  el usuario  en relación con la atención y/o servicio recibido.");
        JRBQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBQuejaActionPerformed(evt);
            }
        });

        Tipoqueja.add(JRBReclamo);
        JRBReclamo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        JRBReclamo.setText("RECLAMO: Expresión de inconformidad por parte del usuario  ante el incumplimiento de una garantía implícita o explícita del servicio.");
        JRBReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBReclamoActionPerformed(evt);
            }
        });

        Tipoqueja.add(JRBsuge);
        JRBsuge.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        JRBsuge.setText("SUGERENCIA: Aquella proposición o idea que aporta el usuario para aumentar su satisfacción en la prestación del servicio.\t");
        JRBsuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBsugeActionPerformed(evt);
            }
        });

        Tipoqueja.add(JRBpeticion);
        JRBpeticion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        JRBpeticion.setText("PETICION: Es aquella solicitud de aclaración, explicación o información del usuario respecto a la prestación o realización de un servicio  en especial.\t");
        JRBpeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBpeticionActionPerformed(evt);
            }
        });

        anexo.add(JRBanexosi);
        JRBanexosi.setText("Si");
        JRBanexosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBanexosiActionPerformed(evt);
            }
        });

        anexo.add(JRBanexono);
        JRBanexono.setText("No");
        JRBanexono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBanexonoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Descripcion");

        JtxtDescrip2.setColumns(20);
        JtxtDescrip2.setRows(5);
        jScrollPane2.setViewportView(JtxtDescrip2);

        jLabel12.setText("Imagen:");

        Jtxtimagen.setEnabled(false);

        jBtnseleccionar.setText("Seleccionar");
        jBtnseleccionar.setEnabled(false);
        jBtnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnseleccionarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Cargo:");

        recibo.add(JRBreciformato);
        JRBreciformato.setText("Recibida en formato no institucional");

        recibo.add(JRBrecimail);
        JRBrecimail.setText("Recibida via E-mail");
        JRBrecimail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBrecimailActionPerformed(evt);
            }
        });

        recibo.add(JRBrecitele);
        JRBrecitele.setText("Recibida telefónicamente");

        jLabel14.setText("Anexa algun documento:");

        JCBCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        JCBCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBCargoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Nombre de quien recibe:");

        JCBfuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        JCBfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBfuncionarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Apellido:");

        JTxtApellido.setEnabled(false);
        JTxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtApellidoKeyTyped(evt);
            }
        });

        JtxtTipousuario.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("No.");

        JtxtNo.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Tipo de Persona");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRBReclamo)
                            .addComponent(JRBQueja)
                            .addComponent(JRBmanifes)
                            .addComponent(JRBpeticion)
                            .addComponent(JRBsuge)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(6, 6, 6)
                                .addComponent(JRBanexosi)
                                .addGap(2, 2, 2)
                                .addComponent(JRBanexono)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(Jtxtimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jBtnseleccionar)
                                .addGap(18, 18, 18)
                                .addComponent(JlblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jLabel11))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(JRBrecimail)
                                .addGap(27, 27, 27)
                                .addComponent(JRBrecitele)
                                .addGap(35, 35, 35)
                                .addComponent(JRBreciformato))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel15)
                                .addGap(14, 14, 14)
                                .addComponent(JCBfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel13)
                                .addGap(14, 14, 14)
                                .addComponent(JCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JtxtDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(JtxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtxtTel)
                                    .addComponent(JtxtTipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Jtxtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(181, 181, 181)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JtxtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JtxtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(JTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Jtxtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(JtxtDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JtxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtxtTipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))))
                    .addComponent(jLabel3)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JRBReclamo))
                    .addComponent(JRBQueja)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(JRBmanifes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(JRBpeticion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JRBsuge)))
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JRBanexosi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JRBanexono))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Jtxtimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jBtnseleccionar))
                    .addComponent(JlblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRBrecimail)
                    .addComponent(JRBrecitele)
                    .addComponent(JRBreciformato))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(JCBfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(JCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnguardar)
                .addGap(19, 19, 19)
                .addComponent(btnactualizar)
                .addGap(15, 15, 15)
                .addComponent(btncancelar)
                .addGap(184, 184, 184))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btnactualizar)
                    .addComponent(btncancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBfuncionarioActionPerformed

    private void JCBCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBCargoActionPerformed

    private void jBtnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnseleccionarActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta = new File("C:/Users/Sala221/Pictures");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION){

            File file = archivo.getSelectedFile();
            Jtxtimagen.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(Jtxtimagen.getText());
            foto = foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            JlblFoto.setIcon(new ImageIcon(foto));

        }
    }//GEN-LAST:event_jBtnseleccionarActionPerformed

    private void JRBpeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBpeticionActionPerformed
        // TODO add your handling code here:
        
        tipoqueja = "Peticion";
        
    }//GEN-LAST:event_JRBpeticionActionPerformed

    private void JRBReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBReclamoActionPerformed
        // TODO add your handling code here:
        
          tipoqueja = "Reclamo";
    }//GEN-LAST:event_JRBReclamoActionPerformed

    private void JRBQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBQuejaActionPerformed
        // TODO add your handling code here:
        
          tipoqueja = "Queja";
        
    }//GEN-LAST:event_JRBQuejaActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
       
      
      
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
      

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:

//        try {
//            //estas sentencia ya lo explique en insertar datos que esta mas arriba
//            FileInputStream  archivofoto;
//            File nombre= new File(txtnomimagen.getText());
//            archivofoto = new FileInputStream(nombre);
//            String sql="UPDATE productos SET cod_pro = ?, "
//            + "des_pro = ?,"
//            + "pre_pro = ?,"
//            + "nomimagen = ?,"
//            + "imagen=?"
//            + "WHERE cod_pro = '"+txtcod.getText()+"'";
//
//            PreparedStatement pst = cn.prepareStatement(sql);
//            pst.setString(1, txtcod.getText());
//            pst.setString(2, txtdes.getText());
//            pst.setString(3, txtpre.getText());
//            pst.setString(4, txtnomimagen.getText());
//            archivofoto = new FileInputStream(txtnomimagen.getText());
//            pst.setBinaryStream(5, archivofoto);
//
//            int n= pst.executeUpdate();
//            if(n>0)
//            {
//                JOptionPane.showMessageDialog(null, "Datos actualizados con exito");
//                bloquear();
//                cargar();
//                limpiar();
//                txtnomimagen.setText(null);
//                lblfoto.setIcon(null);
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "Hubo error en el momento de actualizar los datos");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
//        bloquear();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void JtxtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtdocumentoKeyTyped
        // TODO add your handling code here:
        
        int longitud = this.Jtxtdocumento.getText().length() + 1;
        
        if(!Character.isDigit(evt.getKeyChar()) || longitud > 11)
            evt.consume();
    }//GEN-LAST:event_JtxtdocumentoKeyTyped

    private void JtxtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtnombreKeyTyped
        // TODO add your handling code here:
        
          int longitud = this.Jtxtnombre.getText().length() + 1;
        
        if(Character.isDigit(evt.getKeyChar()) || longitud > 25)
            evt.consume();
    }//GEN-LAST:event_JtxtnombreKeyTyped

    private void JtxtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtTelKeyTyped
        // TODO add your handling code here:
        
           int longitud = this.JtxtTel.getText().length() + 1;
        
        if(Character.isDigit(evt.getKeyChar()) || longitud > 25)
            evt.consume();
    }//GEN-LAST:event_JtxtTelKeyTyped

    private void JtxtCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtCelKeyTyped
        // TODO add your handling code here:
        
        int longitud = this.JtxtCel.getText().length() + 1;
        
        if(Character.isDigit(evt.getKeyChar()) || longitud > 25)
            evt.consume();
    }//GEN-LAST:event_JtxtCelKeyTyped

    private void JtxtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtMailActionPerformed
        // TODO add your handling code here:
        isEmail(String.valueOf(JtxtMail));
        
    }//GEN-LAST:event_JtxtMailActionPerformed

    private void JTxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtApellidoKeyTyped
        // TODO add your handling code here:
        
        int longitud = this.JTxtApellido.getText().length() + 1;
        
        if(Character.isDigit(evt.getKeyChar()) || longitud > 25)
            evt.consume();
    }//GEN-LAST:event_JTxtApellidoKeyTyped

    private void JRBsugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBsugeActionPerformed
        // TODO add your handling code here:
        
         tipoqueja = "Sugerencia";
         
    }//GEN-LAST:event_JRBsugeActionPerformed

    private void JRBmanifesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBmanifesActionPerformed
        // TODO add your handling code here:
        
         tipoqueja = "Manifestacion de satisfaccion";
    }//GEN-LAST:event_JRBmanifesActionPerformed

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusLost

    private void JtxtdocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtxtdocumentoFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_JtxtdocumentoFocusLost

    private void JRBanexosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBanexosiActionPerformed
        // TODO add your handling code here:
        
        jBtnseleccionar.setEnabled(true);
        Jtxtimagen.setEnabled(true);
    }//GEN-LAST:event_JRBanexosiActionPerformed

    private void JRBanexonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBanexonoActionPerformed
        // TODO add your handling code here:
        
        jBtnseleccionar.setEnabled(false);
        Jtxtimagen.setEnabled(false);
    }//GEN-LAST:event_JRBanexonoActionPerformed

    private void JRBrecimailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBrecimailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBrecimailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPQRSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPQRSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPQRSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPQRSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevoPQRSM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser Fecha;
    public javax.swing.JComboBox JCBCargo;
    public javax.swing.JComboBox JCBfuncionario;
    private javax.swing.JRadioButton JRBQueja;
    public javax.swing.JRadioButton JRBReclamo;
    public javax.swing.JRadioButton JRBanexono;
    public javax.swing.JRadioButton JRBanexosi;
    public javax.swing.JRadioButton JRBmanifes;
    public javax.swing.JRadioButton JRBpeticion;
    public javax.swing.JRadioButton JRBreciformato;
    public javax.swing.JRadioButton JRBrecimail;
    public javax.swing.JRadioButton JRBrecitele;
    public javax.swing.JRadioButton JRBsuge;
    public javax.swing.JTextField JTxtApellido;
    private javax.swing.JLabel JlblFoto;
    public javax.swing.JTextField JtxtCel;
    public javax.swing.JTextArea JtxtDescrip2;
    public javax.swing.JTextField JtxtDirecc;
    public javax.swing.JTextField JtxtMail;
    public javax.swing.JTextField JtxtNo;
    public javax.swing.JTextField JtxtTel;
    public javax.swing.JTextField JtxtTipousuario;
    public javax.swing.JTextArea Jtxtdescrip;
    public javax.swing.JTextField Jtxtdocumento;
    public javax.swing.JTextField Jtxtimagen;
    public javax.swing.JTextField Jtxtnombre;
    private javax.swing.ButtonGroup Tipoqueja;
    private javax.swing.ButtonGroup anexo;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JButton jBtnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.ButtonGroup recibo;
    private javax.swing.ButtonGroup tipouser;
    // End of variables declaration//GEN-END:variables
}
