/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Sala221
 */
public class NuevoUsiario extends javax.swing.JFrame {
    
      public String tipopersona = "";
       
    /**
     * Creates new form NuevoPQRSM
     */
    public NuevoUsiario() {
        initComponents();
    }
    
//    void limpiar(){
//        JtxtCel.setText(null);
//      
//        JtxtDirecc.setText(null);
//        JtxtMail.setText(null);
//        JtxtTel.setText(null);
//        Jtxtdocumento.setText(null);
//        Jtxtnombre.setText(null);
//        JTxtApellido.setText(null);
//    }
    
    public boolean isEmail(String correo){
            Pattern pat = null;
            Matcher mat =null;
            pat = Pattern.compile("^([0-9a-zA-Z]([_.W]*[0-9a-zA-Z])*@8[0-9a-zA-Z]"
                                  +"[-W]*[0-9a-Za-z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
            mat = pat.matcher(correo);
            if (mat.find()){
                return true;
            }
            else{
                return false;
            }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipouser = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MODIFICAR = new javax.swing.JMenuItem();
        jLabel41 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblUsuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        JRBestuiante = new javax.swing.JRadioButton();
        JRBFamiEstu = new javax.swing.JRadioButton();
        JRBVisitante = new javax.swing.JRadioButton();
        JRBProveedor = new javax.swing.JRadioButton();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtdocu = new javax.swing.JTextField();
        jtxtdirecc = new javax.swing.JTextField();
        jtxtMail = new javax.swing.JTextField();
        jtxtcelular = new javax.swing.JTextField();
        jBtnAgregar = new javax.swing.JButton();
        jBtnVer = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnAdicionar = new javax.swing.JButton();
        jbtnactualizar = new javax.swing.JButton();

        MODIFICAR.setText("Modificar");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MODIFICAR);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(784, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("E-Mail:");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Documento:");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Nombre:");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Apellido:");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Direccion:");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Telefono:");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Celular:");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel34.setText("REGISTRO DE NUEVA PERSONA");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 390, -1));

        jTblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblUsuarios.setComponentPopupMenu(jPopupMenu1);
        jScrollPane4.setViewportView(jTblUsuarios);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 720, 180));

        tipouser.add(JRBestuiante);
        JRBestuiante.setText("Estudiante");
        JRBestuiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBestuianteActionPerformed(evt);
            }
        });
        getContentPane().add(JRBestuiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        tipouser.add(JRBFamiEstu);
        JRBFamiEstu.setText("Familiar estudiante");
        JRBFamiEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBFamiEstuActionPerformed(evt);
            }
        });
        getContentPane().add(JRBFamiEstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        tipouser.add(JRBVisitante);
        JRBVisitante.setText("Visitante");
        JRBVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBVisitanteActionPerformed(evt);
            }
        });
        getContentPane().add(JRBVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        tipouser.add(JRBProveedor);
        JRBProveedor.setText("Proveedor");
        JRBProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(JRBProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 220, -1));

        jtxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApellidoActionPerformed(evt);
            }
        });
        jtxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 200, -1));

        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 100, -1));

        jtxtdocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdocuActionPerformed(evt);
            }
        });
        jtxtdocu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtdocuKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtdocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, -1));
        getContentPane().add(jtxtdirecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 390, -1));

        jtxtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMailActionPerformed(evt);
            }
        });
        jtxtMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMailKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 440, -1));

        jtxtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcelularKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 160, -1));

        jBtnAgregar.setText("Agregar Usuarios");
        getContentPane().add(jBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jBtnVer.setText("Ver Usuarios");
        jBtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jBtnEliminar.setText("Eliminar Usuarios");
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        jBtnAdicionar.setText("Adicionar Usuarios");
        jBtnAdicionar.setEnabled(false);
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jbtnactualizar.setText("Actualizar");
        jbtnactualizar.setEnabled(false);
        getContentPane().add(jbtnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBestuianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBestuianteActionPerformed
        // TODO add your handling code here:

        tipopersona = "Estudiante";
    }//GEN-LAST:event_JRBestuianteActionPerformed

    private void JRBFamiEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBFamiEstuActionPerformed
        // TODO add your handling code here:

        tipopersona = "Familiar Estudiante";
    }//GEN-LAST:event_JRBFamiEstuActionPerformed

    private void JRBVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBVisitanteActionPerformed
        // TODO add your handling code here:

        tipopersona = "Visitante";
    }//GEN-LAST:event_JRBVisitanteActionPerformed

    private void JRBProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBProveedorActionPerformed
        // TODO add your handling code here:

        tipopersona = "Proveedor";
    }//GEN-LAST:event_JRBProveedorActionPerformed

    private void jtxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidoActionPerformed

    private void jtxtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMailActionPerformed

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        // TODO add your handling code here:
        
        int longitud = this.jtxtNombre.getText().length() + 1;
        
        if(longitud > 60 || Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoKeyTyped
        // TODO add your handling code here:
        int longitud = this.jtxtApellido.getText().length() + 1;
        
        if(longitud > 60 || Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_jtxtApellidoKeyTyped

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped

        int longitud = this.jtxtTelefono.getText().length() + 1;
        
        if(!Character.isDigit(evt.getKeyChar()) || longitud > 7)
            evt.consume();
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtdocuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdocuKeyTyped
        // TODO add your handling code here:
        
        int longitud = this.jtxtdocu.getText().length() + 1;
        
        if(!Character.isDigit(evt.getKeyChar()) || longitud > 11)
            evt.consume();
    }//GEN-LAST:event_jtxtdocuKeyTyped

    private void jtxtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcelularKeyTyped
        // TODO add your handling code here:
        
        int longitud = this.jtxtcelular.getText().length() + 1;
        
        if(!Character.isDigit(evt.getKeyChar()) || longitud > 11)
            evt.consume();
    }//GEN-LAST:event_jtxtcelularKeyTyped

    private void jtxtMailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMailKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtxtMailKeyTyped

    private void jBtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnVerActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void jtxtdocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdocuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton JRBFamiEstu;
    public javax.swing.JRadioButton JRBProveedor;
    public javax.swing.JRadioButton JRBVisitante;
    public javax.swing.JRadioButton JRBestuiante;
    public javax.swing.JMenuItem MODIFICAR;
    public javax.swing.JButton jBtnAdicionar;
    public javax.swing.JButton jBtnAgregar;
    public javax.swing.JButton jBtnEliminar;
    public javax.swing.JButton jBtnVer;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTblUsuarios;
    public javax.swing.JButton jbtnactualizar;
    public javax.swing.JTextField jtxtApellido;
    public javax.swing.JTextField jtxtMail;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtTelefono;
    public javax.swing.JTextField jtxtcelular;
    public javax.swing.JTextField jtxtdirecc;
    public javax.swing.JTextField jtxtdocu;
    public javax.swing.ButtonGroup tipouser;
    // End of variables declaration//GEN-END:variables
}
