/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

/**
 *
 * @author Sala221
 */
public class nuevoTratamiento extends javax.swing.JFrame {
    
    public String Cierre = "";

    /**
     * Creates new form nuevoseguimiento
     */
    public nuevoTratamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cierrequeja = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MODIFICAR = new javax.swing.JMenuItem();
        jBtnVer = new javax.swing.JButton();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jbtnactualizar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtcoditrata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtcodiPQRSM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextojustificacion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbltratamiento = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel10 = new javax.swing.JLabel();
        jtxtcodifuncio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JCBfuncionario = new javax.swing.JComboBox();

        MODIFICAR.setText("Modificar");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MODIFICAR);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnVer.setText("Ver Usuarios");
        jBtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jBtnAdicionar.setText("Adicionar Usuarios");
        jBtnAdicionar.setEnabled(false);
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, -1, -1));

        jBtnAgregar.setText("Agregar Usuarios");
        getContentPane().add(jBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, -1, -1));

        jbtnactualizar.setText("Actualizar");
        jbtnactualizar.setEnabled(false);
        getContentPane().add(jbtnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        jBtnEliminar.setText("Eliminar Usuarios");
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel34.setText("REGISTRO DE NUEVO TRATAMIENTO");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 450, -1));

        jLabel1.setText("Numero de tratamiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));
        getContentPane().add(jtxtcoditrata, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 30, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Numero del PQRSM:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(jtxtcodiPQRSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 30, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Justificacion del area asignada:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTextojustificacion.setColumns(20);
        jTextojustificacion.setRows(5);
        jScrollPane1.setViewportView(jTextojustificacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 750, 80));

        jTbltratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbltratamiento.setComponentPopupMenu(jPopupMenu1);
        jScrollPane3.setViewportView(jTbltratamiento);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 720, 250));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Numero del funcionario:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        getContentPane().add(jtxtcodifuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 30, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Nombre del funcionario:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        JCBfuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        JCBfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(JCBfuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnVerActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MODIFICARActionPerformed

    private void JCBfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBfuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoTratamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox JCBfuncionario;
    public javax.swing.JMenuItem MODIFICAR;
    public javax.swing.ButtonGroup cierrequeja;
    public javax.swing.JButton jBtnAdicionar;
    public javax.swing.JButton jBtnAgregar;
    public javax.swing.JButton jBtnEliminar;
    public javax.swing.JButton jBtnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTbltratamiento;
    public javax.swing.JTextArea jTextojustificacion;
    public javax.swing.JButton jbtnactualizar;
    public javax.swing.JTextField jtxtcodiPQRSM;
    public javax.swing.JTextField jtxtcodifuncio;
    public javax.swing.JTextField jtxtcoditrata;
    // End of variables declaration//GEN-END:variables
}
